apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    env: test
  ports:
  - protocol: TCP
    port: 1234
    targetPort: 8080
    #NodePort:  ranging from 30000-32767 , 312
  type: NodePort
